# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-18 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_remove_neighbourhood_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
