# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-18 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_neighbourhood_hood_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='health_contact',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='police_contact',
            field=models.CharField(max_length=30),
        ),
    ]
